### PR TITLE
Add y axis to brush selection

### PR DESCRIPTION
**Pull request by lrennels**
@davidanthoff this addresses #402 by including the y axis in the brush selection.  If we wanted to just brush the x axis and have the y axis scale automatically, there may be a way to filter the data as we go and then change the y axis based on the new selection.  VegaLite warns that this is less efficient, since it involves constantly evaluating the data based on the changing conditions as opposed to just using the same data and a new scale, but I think it would be doable.  This might be preferred if it is too tedious to select for clumped-together, low y values.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Yeah, I think it would be nicer if the selection was only for the x axis, and then the height of the y axis automatically adjusted based on the min and max value in the selected x axis region. Maybe we can try whether that has performance issues, and only if it does, go with this PR here?

**Comment by lrennels** [comment]
Sure, for my reference see Selection Predicate here: https://vega.github.io/vega-lite/docs/filter.html

**Comment by lrennels** [comment]
@davidanthoff Alright this should do the trick.  Note that in this version, you must brush over at least two year intervals (so ten years here since we have 5 year intervals) for anything to show up.  It seems that VegaLite is off-by-one on the x axis, showing labels 2014 to 2109 for the example instead of 2015 to 2110.  I'll work on figuring that out.

**Comment by lrennels** [comment]
off-by-one error solved using `"timeUnit" => "utcyear"` instead of `"timeUnit" => "year"` see https://github.com/vega/vega-lite/issues/4044

**Pull request merged**
