### PR TITLE
Separate set_models! from run_mcs

### PR DESCRIPTION
**Pull request by rjplevin**
Partial fix for `run_mcs` issue. @lrennels should take a look...

### CODE REVIEW

**Comment by lrennels** [comment]
@rjplevin per our conversation we need a bit of design discussion for this.  Our incrementing idea doesn't quite hold because calling `run_mcs(mcs, m, ...)` multiple times keeps incrementing the `models_to_run` without checking if `m` is an element of `models_to_run`.  One solution would be to separate steps so that a user has to (1) `set_model(s)!` and (2) `run_mcs`.  That would allow `run_mcs` to take the argument `models_to_run` indicating the **indices** of the models the user wants to run without the complication of calling `set_model!` within `run_mcs`.  Thoughts?

**Comment by rjplevin** [comment]
I agree. This simplifies the API and avoids hard-to-explain workarounds. Will you do this? (Thanks!)

**Comment by lrennels** [comment]
@rjplevin sure I'll do it, I might also remove `set_model` and just use`set_models!` function with two methods, one for a single model and one for a vector of models.

**Comment by lrennels** [comment]
Similarly, should `models_to_run` be the first n models, or should we allow users to pick which models?  Just throwing out design decisions that seem like they need to be wrapped up!

**Pull request merged**
